### PR TITLE
Update Rock3a kernel 5.10 and uboot 2023.10

### PR DESCRIPTION
**Pull request by haelyons**
- Update to latest 5.10 kernel from radxa
- Update uboot to 2023.10 (latest from radxa also)
- Change sourcing for overlays - no longer provided in kernel due to update, so add them in the board dir and copy during post-image
- Uboot ITB now directly copied from Uboot build directory 
- Remove previous patches to kernel (no longer necessary)
- Add libmraa GPIO library with Rock 3A support (reccent)

### CODE REVIEW

**Comment by nkiryushin** [comment]
For me, there were a couple of issues, while building this version

1) rkbin package needs to be built before building uboot or kernel, but there are no dependencies in the packages. `make rkbin` before `make` will help with this issue;
2) newer version of uboot and kernel leads to some new configuration options not being set, which leads to interactive prompts;
3) newer uboot needs swig, probably this should be documented in dependency section of readme (somehow installing swig to my _host_, running buildroot, did it for me, not sure if it is the right way - my assumption is that swig should be a toolchain dependency, added as host-swig dependency to uboot package and should be run from buildroot toolchain, not host system);
4) uboot configuration hangs after first run with merged config, stating it needs the user to "run Make", on second run configuration continues with interactive prompts (see n 2)

The issues are minor and easy to overcome, but they break running builds in automated headless toolchain

**Comment by haelyons** [comment]
1. Not sure how to make `rkbin` be built automatically before kernel -- my instinct would be to manually patch the main Buildroot tree to add it as a depedendency, or in the build hooks, but this is not a clean solution, and I reckon most people would rather avoid it
2. Removing the U-Boot environment parameters from the fragment seemed to remove the interactive prompts after a `make clean`. Have not been able to reproduce U-Boot hanging issue after a reclone and `make`.
3. As you can't patch in-tree package makefiles automatically I've just added swig to the README for the host to install. This worked for me on a fresh WSL distro.

Thanks for taking the time to build :) agree that it should ideally run headless. Next TODO is to compile the Radxa overlays at build-time instead of having all the files in `/board/` directory.

**Review by flatmax — CHANGES_REQUESTED** [review]
We shouldn't commit binary files - they are generated by the software. Can you please remove all binaries from this commit ?

**Review by flatmax — COMMENTED** [review]
OK - I see that you've removed dtbo files, these changes look pretty good. I will do a test build.

**Comment by flatmax** [comment]
Got it thanks - you should update the readme with that information for the rock3a only.

I tried to boot and this is as far as I got :
```
U-Boot 2023.10 (Feb 21 2024 - 08:27:40 +1100)

Model: Radxa ROCK3 Model A
DRAM:  4 GiB (effective 3.7 GiB)
PMIC:  RK8090 (on=0x40, off=0x00)
```

**Comment by haelyons** [comment]
Huh that's very strange -- all mine are 1.31, just tried on a clean one after a full-rebuild and no issues booting 🤔

**Comment by RadxaYuntian** [comment]
Hi @flatmax , can you send the front and back pictures of your unbootable ROCK 3A 1.31 so we can inspect the hardware? You can send to yt@radxa.com so we don't distract this PR too much.

**Comment by RadxaYuntian** [comment]
I have received the picture and it is using memory from CXMT (the black rectangle chip next to the SoC). Usually when we get boot issues in U-Boot it was due to memory compatibility, so @flatmax and @haelyons can you check what memory manufacturer is used on your working 3As?

It might also be worth to upgrade the included rkbin to see if that solves the issue. We are currently using radxa/rkbin@fc44f9401c127affb2a879c1e90fa89ddab505f6 which is tracked [here](https://github.com/radxa-repo/bsp/blob/main/u-boot/.rockchip/rkbin.sh#L10). The specific files are matched with [following substrings](https://github.com/radxa-repo/bsp/blob/main/u-boot/latest/fork.conf#L101-L102) with priority given to newer versions:

https://github.com/radxa/rkbin/blob/fc44f9401c127affb2a879c1e90fa89ddab505f6/bin/rk35/rk3568_bl31_set_pmic_sleep_low_20221018_v1.32.elf
https://github.com/radxa/rkbin/blob/fc44f9401c127affb2a879c1e90fa89ddab505f6/bin/rk35/rk3568_ddr_1560MHz_v1.19.bin

@flatmax can you try [this image](https://github.com/radxa-build/rock-3a/releases/download/b25/rock-3a_debian_bullseye_xfce_b25.img.xz) to see if it can boot on your device? If it works you can see if upgrading rkbin solves the issue for you.

**Comment by nkiryushin** [comment]
@RadxaYuntian my ROCK 3A 1.31 boots fine with binaries in this PR, it has SKhynix ram chip

**Comment by flatmax** [comment]
I just did a fresh test build - so that I could look at the rkbin updates.

Unfortunately the overlay files are no longer being copied over to the output/image/rockchip/overlays directory ....
Is it working in your repo @haelyons ?

**Comment by haelyons** [comment]
@flatmax checked this morning and when switched to master branch and pulled my post-image didn't update properly, but with a fresh clone it works fine -- does your `/board/RK3568/post-image.sh` match the changes in master? [Should look like this](https://github.com/flatmax/buildroot.rockchip/blob/master/board/RK3568/post-image.sh). 

@RadxaYuntian my 1.31s all have SEC 222 GHN1856DU

**Comment by flatmax** [comment]
YEah - the dtbo files are present in the Linux directory but not copied over to the images directory for some reason

**Comment by RadxaYuntian** [comment]
> SEC 222 GHN1856DU

That sounds like a Samsung. It should have a QR code on the chip as well.

**Comment by flatmax** [comment]
Hey there - I have switched to a more recent rkbin version. @haelyons could you do a test build ?

@RadxaYuntian I have the most recent DDR file now for the rock3a and I still have trouble booting off sdcard with the v1.31 board. The v1.3 board works fine.

**Comment by RadxaYuntian** [comment]
Did you test our image as well?

**Comment by flatmax** [comment]
oh note sure. What is your image ?

**Comment by RadxaYuntian** [comment]
> @flatmax can you try [this image](https://github.com/radxa-build/rock-3a/releases/download/b25/rock-3a_debian_bullseye_xfce_b25.img.xz) to see if it can boot on your device? If it works you can see if upgrading rkbin solves the issue for you.

mentioned here

**Pull request merged**
